FROM python:3.11-slim

WORKDIR /app

COPY scraper/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY shared /app/shared
COPY scraper /app/scraper

ENV PYTHONPATH=/app

CMD ["python", "-m", "scraper.scraper"]
